# #######################################
# Model: wav2vec2 for Emotion Diarization
# Authors: 
#  * Yingzhi Wang 2023
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 12
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/wav2vec_base_0.2_0.2/<seed>
cer_file: !ref <output_folder>/cer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# wav2vec2_hub: "LeBenchmark/wav2vec2-FR-3K-base"
wav2vec2_hub: "facebook/wav2vec2-base"
# wav2vec2_hub: "facebook/hubert-base-ls960"

# Data files
zed_folder: /projects/ywang/research_emo_db/ZED_final_1

emovdb_folder: /rd_storage/yingzhi_koios/emotion_datasets/EmoV-DB/
esd_folder: /rd_storage/yingzhi_koios/emotion_datasets/ESD/
iemocap_folder: /rd_storage/yingzhi_koios/emotion_datasets/IEMOCAP_full_release/
jlcorpus_folder: /rd_storage/yingzhi_koios/emotion_datasets/JL_corpus/
ravdess_folder: /rd_storage/yingzhi_koios/emotion_datasets/RAVDESS/

split_ratio: [90, 10]

train_annotation: !ref <output_folder>/train.json
valid_annotation: !ref <output_folder>/valid.json
test_annotation: !ref <output_folder>/test.json

ckpt_interval_minutes: 15 # save checkpoint every N min
# Training parameters
number_of_epochs: 30
lr: 0.0001
lr_wav2vec: 0.00001
sorting: ascending
# auto_mix_prec: False
# do_resample: False
sample_rate: 16000

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 3 per GPU to fit 32GB of VRAM
batch_size: 4
test_batch_size: 1

# Dataloader options
dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: True
    num_workers: 2  # 2 on linux but 0 works on windows
    drop_last: False

test_dataloader_opts:
   batch_size: !ref <test_batch_size>

# Model parameters
activation: !name:torch.nn.LeakyReLU
# dnn_layers: 2

#freeze all wav2vec2
freeze_wav2vec2: False
freeze_wav2vec2_conv: True

window_length: 10 # win_len = 0.02 * 10 = 0.2s
stride: 10 # stride = 0.02 * 10 = 0.2s

encoder_dim: 768
# Outputs
out_n_neurons: 5  # BPE size, index(blank/eos/bos) = 0

# # DER evaluation parameters
# ignore_overlap: True
# forgiveness_collar: 0.25

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec2>
    freeze_feature_extractor: !ref <freeze_wav2vec2_conv>
    save_path: !ref <save_folder>/wav2vec2_checkpoint
    # output_all_hiddens: False

avg_pool: !new:speechbrain.nnet.pooling.Pooling1d
    pool_type: "avg"
    kernel_size: !ref <window_length>
    stride: !ref <stride>
    ceil_mode: True

output_mlp: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <encoder_dim>
    n_neurons: !ref <out_n_neurons>
    bias: False

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.nll_loss

modules:
    wav2vec2: !ref <wav2vec2>
    output_mlp: !ref <output_mlp>

model: !new:torch.nn.ModuleList
    - [!ref <output_mlp>]

model_opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr>
    rho: 0.95
    eps: 1.e-8

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wav2vec2_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

lr_annealing_wav2vec2: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec>
    improvement_threshold: 0.0025
    annealing_factor: 0.9
    patient: 0


checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        wav2vec2: !ref <wav2vec2>
        model: !ref <model>
        scheduler_model: !ref <lr_annealing>
        scheduler_wav2vec: !ref <lr_annealing_wav2vec2>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch
